name: CI

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  unciv-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: oxipng image compression
        run: | 
          oxipng_url=$(curl -sL https://api.github.com/repos/shssoichiro/oxipng/releases/latest | grep -o "http.*x86_64-unknown-linux-gnu.tar.gz")
          wget -O oxipng.tar.gz $oxipng_url
          tar -xvzf oxipng.tar.gz
          rm oxipng.tar.gz
          
          oxipng_file=$(find oxipng* | grep "/oxipng")
          find Images* -type f -regex ".*png" | xargs -d '\n' $oxipng_file --opt max --strip all --alpha
          rm -rf $(ls -1 | grep oxipng)

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Autoupdate
        continue-on-error: true
        run: |
          unciv_url=$(curl -s https://api.github.com/repos/yairm210/unciv/releases/latest | grep -o "http.*Unciv.jar")
          wget -q -O Unciv.jar $unciv_url
          java -jar Unciv.jar mod-ci

      - name: Remove Unciv executable
        run: rm Unciv.jar

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Autoupdate
